SELECT ROUTINE_NAME, ROUTINE_DEFINITION
    FROM INFORMATION_SCHEMA.ROUTINES 
    WHERE ROUTINE_DEFINITION LIKE '%OffreProduit%'
	OR ROUTINE_DEFINITION LIKE '%NiveauPerf%'
    AND ROUTINE_TYPE='PROCEDURE'